# https://github.com/Live-GM/api/blob/fd26d8efa46b101deba47d45061542ac0d76142f/.github/workflows/main.yml
name: CI

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: 'Build'
        run: 'yarn ci'
      - name: 'Deploy'
        env:
          GH_TOKEN: ${{secrets.GH_TOKEN}}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
        run: 'yarn semantic-release'
